clear;
close all;

traffic_sign_recognition_1_0_settings;

traffic_sign_recognition_1_1_cropResizeImgs_plus_datasetSplit;

traffic_sign_recognition_2_sift;

traffic_sign_recognition_3_clustering_plus_BoF;

traffic_sign_recognition_4_img_classification;